[package]
name = "android_rust_sample"
version = "0.1.0"
edition = "2021"


[lib]
name = "android_rust_sample"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
jni = { version = "0.21.1", default-features = false }
thiserror = "1"
